<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Удаленные вакансии',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '%d0%be%d0%bf%d0%bb%d0%b0%d1%82%d0%b01.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'termo2plast@gmail.com',
		'to' => 'termo2plast@gmail.com'
	),
	'fields' => array(
		'custom_U5232' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Фамилия, Имя, Отчество',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Фамилия, Имя, Отчество\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Электронная почта',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Электронная почта\' не может быть пустым.',
				'format' => 'Поле \'Электронная почта\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U5282' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Домашний адрес',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Домашний адрес\' не может быть пустым.'
			)
		),
		'custom_U5294' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Город',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Город\' не может быть пустым.'
			)
		),
		'custom_U5306' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Область',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Область\' не может быть пустым.'
			)
		),
		'custom_U5318' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Почтовый индекс, номер отделения',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Почтовый индекс, номер отделения\' не может быть пустым.'
			)
		),
		'custom_U5371' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Сотовый телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сотовый телефон\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
